const SUPABASE_URL="https://npovzdaxuvxeqgdougqh.supabase.co";const SUPABASE_PUBLISHABLE_KEY="sb_publishable_I4EkQQuOkGmXAf7Mb1wWKw_xSx-HM6p";const supabase=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);const $=id=>document.getElementById(id);let currentUser=null,currentLeader=null,actions=[],entries=[];
$("loginForm").addEventListener("submit",async e=>{e.preventDefault();$("loginError").textContent="";const{error}=await supabase.auth.signInWithPassword({email:$("email").value.trim(),password:$("password").value});if(error)$("loginError").textContent=error.message});
$("logoutBtn").addEventListener("click",async()=>{await supabase.auth.signOut();showLogin()});$("refreshBtn").addEventListener("click",loadDashboard);$("closeModal").addEventListener("click",()=>$("entryModal").classList.add("hidden"));$("entryForm").addEventListener("submit",saveEntry);
supabase.auth.onAuthStateChange((_e,s)=>{if(s?.user){currentUser=s.user;loadDashboard()}else showLogin()});init();
async function init(){const{data}=await supabase.auth.getSession();if(data.session?.user){currentUser=data.session.user;await loadDashboard()}else showLogin()}
async function loadDashboard(){if(!currentUser)return;$("loginView").classList.add("hidden");$("dashboardView").classList.remove("hidden");const{data:leader,error:le}=await supabase.from("leaders").select("*").eq("user_id",currentUser.id).maybeSingle();if(le){showMessage("Could not load your profile: "+le.message);return}if(!leader){$("userLabel").textContent=currentUser.email||"";showMessage("Your login works, but it is not linked to a leadership profile yet.");return}currentLeader=leader;$("userLabel").textContent=leader.name+" • "+leader.role.toUpperCase();const{data:a,error:ae}=await supabase.from("actions").select("*").order("id");if(ae){showMessage(ae.message);return}actions=a||[];const{data:en,error:ee}=await supabase.from("entries").select("id,action_id,done_on,note,created_at").eq("leader_id",leader.id).order("done_on",{ascending:false});if(ee){showMessage(ee.message);return}entries=en||[];renderActions();if(leader.role==="admin")loadAdminOverview();else $("adminSection").classList.add("hidden")}
function renderActions(){const relevant=actions.filter(a=>currentLeader.role==="admin"||(currentLeader.role==="hoi"?a.hoi_q:a.hod_q));const ids=new Set(entries.map(e=>e.action_id));const done=relevant.filter(a=>ids.has(a.id)).length;$("totalActions").textContent=relevant.length;$("completedActions").textContent=done;$("progress").textContent=relevant.length?Math.round(done/relevant.length*100)+"%":"0%";$("actionsList").innerHTML=relevant.map(a=>{const e=entries.find(x=>x.action_id===a.id);return '<div class="action"><div class="action-main"><span class="domain">'+esc(a.domain)+'</span><h3>'+esc(currentLeader.lang==="ar"&&a.name_ar?a.name_ar:a.name_en)+'</h3><p class="evidence">'+esc(a.evidence||"Evidence to be recorded.")+'</p>'+(e?'<div class="done">✓ Completed '+esc(e.done_on)+(e.note?" — "+esc(e.note):"")+"</div>":"")+'</div><button onclick="openModal('+a.id+')">'+(e?"Add another record":"Record evidence")+"</button></div>"}).join("")}
window.openModal=id=>{const a=actions.find(x=>x.id===id);$("modalActionId").value=id;$("modalTitle").textContent=a?(currentLeader.lang==="ar"&&a.name_ar?a.name_ar:a.name_en):"Record evidence";$("doneOn").value=new Date().toISOString().slice(0,10);$("note").value="";$("entryError").textContent="";$("entryModal").classList.remove("hidden")};
async function saveEntry(e){e.preventDefault();const{error}=await supabase.from("entries").insert({leader_id:currentLeader.id,action_id:Number($("modalActionId").value),done_on:$("doneOn").value,note:$("note").value.trim()||null});if(error){$("entryError").textContent=error.message;return}$("entryModal").classList.add("hidden");await loadDashboard()}
async function loadAdminOverview(){const{data,error}=await supabase.from("leaders").select("id,username,name,role,active").order("name");if(error){$("adminTable").textContent=error.message;return}$("adminTable").innerHTML="<div style='padding:20px'>"+(data||[]).map(l=>"<p><b>"+esc(l.name)+"</b> — "+esc(l.role)+" — "+(l.active?"Active":"Inactive")+"</p>").join("")+"</div>"}
function showLogin(){$("dashboardView").classList.add("hidden");$("loginView").classList.remove("hidden");$("password").value=""}function showMessage(t){$("message").textContent=t;$("message").classList.remove("hidden")}function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}